CREATE TABLE [dbo].[FavoriteBeer]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	AppUserId INT,
	BeerId INT

	CONSTRAINT FK_User FOREIGN KEY (AppUserId) REFERENCES AppUser(Id),
	CONSTRAINT FK_Beer FOREIGN KEY (BeerId) REFERENCES Beer(Id)
)
